name: GuydeUtil
main: com.guyde.plug.main.MainClass
version: 1.0
commands: 
   readlua:
      description: Used to reload data
      usage: /<command>
      permission: <plugin name>.admin
      permission-message: You don't have <permission>
   getweapon:
      description: Used to register click handlers in-game
      usage: /<command> [handler-id]
      permission: <plugin name>.admin
      permission-message: You don't have <permission>
   getarmor:
      description: Used to register click handlers in-game
      usage: /<command> [handler-id]
      permission: <plugin name>.admin
      permission-message: You don't have <permission>
   spawnmob:
      description: Used to register click handlers in-game
      usage: /<command> [handler-id]
      permission: <plugin name>.admin
      permission-message: You don't have <permission>
   identify:
      description: Used to register click handlers in-game
      usage: /<command> [handler-id]
      permission: <plugin name>.admin
      permission-message: You don't have <permission>
   class:
      description: Used to register click handlers in-game
      usage: /<command> [handler-id]
      permission: <plugin name>.admin
      permission-message: You don't have <permission>